### Get Hello World
GET http://localhost:3000

### Create an Account
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "silly_user",
  "email": "silly_user@email.com",
  "password": "secret_\\\\>:3"
}

### Login as User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "silly_user@email.com",
  "password": "secret_\\\\>:3"
}

### Refresh Token # This path doesn't work for now.
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "5eb6e10b02f9a9a03049657d88c317a3dc83c78f05e670b1b7b745e33c8de1c8f56ec61b5a7064599b26ea52d6ddee843c32d54bee1a953849be1cc288043246"
}

### Update User
PUT http://localhost:3000/auth/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJzdWIiOiI4YWNmNjc5MS04NzEyLTQ2YTUtYTkwMy02MGY3NjcwMWU3NGEiLCJlbWFpbCI6InNpbGx5LnVzZXJAZW1haWwuY29tIiwiaWF0IjoxNzcxOTQyNTAxLCJleHAiOjE3NzE5NDM0MDF9.cBn3WjnjiTu9E1B4rpRd0-cv6nEO8aghytBeHe7kS0zBrXbLQLXfrmi-qcGfEf5oUXSF44HH5K0uIJld-6B8PFDEs54VgH1NpoMULoiFP68O3Ue67Cr_YpOzUVBa96Hnu2H6uncgl6t5YZ30gdgoS-f0gF5LN4fCeN2FuqAvTe1M86_THT4QKziatU4Sgomt7ZAkBSPdC0Ua11AurKvc8ziXvERLR3yfUwUOFzeTH-IjZpgkq3Pd9fPlHN6_mfD4_ei0s3uAFzzgvBSi_zZ2cUboN1RzuLYENzjQJQMijnabwyrTJGAfPJdxt0Ue9hwPxvfBBEuxNUw7Biznf_HvWw

{
  "id": "8acf6791-8712-46a5-a903-60f76701e74a",
  "username": "silly_user",
  "password": "secret_\\\\>:3"
}

### Delete User
DELETE http://localhost:3000/auth/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJzdWIiOiI4YWNmNjc5MS04NzEyLTQ2YTUtYTkwMy02MGY3NjcwMWU3NGEiLCJlbWFpbCI6InNpbGx5LnVzZXJAZW1haWwuY29tIiwiaWF0IjoxNzcxOTQyNTAxLCJleHAiOjE3NzE5NDM0MDF9.cBn3WjnjiTu9E1B4rpRd0-cv6nEO8aghytBeHe7kS0zBrXbLQLXfrmi-qcGfEf5oUXSF44HH5K0uIJld-6B8PFDEs54VgH1NpoMULoiFP68O3Ue67Cr_YpOzUVBa96Hnu2H6uncgl6t5YZ30gdgoS-f0gF5LN4fCeN2FuqAvTe1M86_THT4QKziatU4Sgomt7ZAkBSPdC0Ua11AurKvc8ziXvERLR3yfUwUOFzeTH-IjZpgkq3Pd9fPlHN6_mfD4_ei0s3uAFzzgvBSi_zZ2cUboN1RzuLYENzjQJQMijnabwyrTJGAfPJdxt0Ue9hwPxvfBBEuxNUw7Biznf_HvWw

{
  "id": "8acf6791-8712-46a5-a903-60f76701e74a",
  "password": "secret_\\\\>:3"
}

### Get Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMjYtMDQtMTkifQ.eyJzdWIiOiIxIiwiZW1haWwiOiJzaWxseV91c2VyIiwiaWF0IjoxNzc2NjA4MTQ4LCJleHAiOjE3NzY2MDkwNDh9.prYqrBjfgIrKeAnxhFr-Y6Tml-nqs1_AdntTOXG1QDGoIt13Ps67fCjtRg7g7U1ZzgS2cey__HS_37leRkIJ2Ym1LDHlA_x0Fi2_RM0sVrUC29eIhDYPZ04ThkA27TVLdGaRKvcIw345ygBSgLInFsgrBo7NVEw9Y-PHxbj6wfcBrxAZ6d_PCkbtQ6D26WUieNegPHudH6jr1FbUI8Ox4c9z-WydYhJ98eu2zlbc33g_h2i_R5PNMQlBmv6U42X0mcIpUFHwu7XMM85eJDiu9hposAh0w6AecizkCDEnCG4L9gLePuM0ErSh0eXWJizz-7I5NvabfjLIwZyM-HLNFQ

### Create a New Plan
POST http://localhost:3000/plan/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMjYtMDQtMTkifQ.eyJzdWIiOiIxIiwiZW1haWwiOiJzaWxseV91c2VyIiwiaWF0IjoxNzc2NjE2MTY0LCJleHAiOjE3NzY2MTcwNjR9.HzeFTIBCSr-WBT3m-6awwxNNikYzwju_X8bCqVI7J6C47ZLnhXaVcgFQyC1ytbnfgQQBSoddNm9yqD4IpLMTyq25RW-kUoYV8sRKbTF5wTLiDtleoucYmbKwYa6Bh-7Xxq1MyZwNUd7K7JHZGIBSraDH-3JECuRm1XHDoxxRySnXuD-xzO36WMo4nmAOkG0HJ5y39bMakBAknECSetE4T7JY6vJcAFxPVv4NydNuqxUrKg7eIE2eIbnCbFp3m0Ty9pRdp_mMiIrZR2K14fuBGcUlrZo0vsJi11ApZUIiTk-EsYVFmJPNxPrEvzPLJjHZAivI5NMwK43SWzD6QGQLBA

{
  "title": "My Plan",
  "tasks": [
    {
      "title": "Task 1",
      "description": "Description for Task 1",
      "effort": "low",
      "duration": 20,
      "priority": 1,
      "isCompleted": false
    },
    {
      "title": "Task 2",
      "description": "Description for Task 2",
      "duration": 30,
      "priority": 2,
      "effort": "medium",
      "isCompleted": false
    },
    {
      "title": "Task 3",
      "description": "Description for Task 3",
      "effort": "high",
      "priority": 3,
      "duration": 50,
      "isCompleted": false
    }
  ]
}

### Update Plan
PUT http://localhost:3000/plan/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMjYtMDQtMTkifQ.eyJzdWIiOiIxIiwiZW1haWwiOiJzaWxseV91c2VyIiwiaWF0IjoxNzc2NjI1NTk5LCJleHAiOjE3NzY2MjY0OTl9.BUzPkAqF_zi285gYPXBnS1op9AuiyheT8dmBhCbyfte9DLvvDTSai6noy7WuTwLsMKQWs4OtcxDjHDPRVWyGz6gtxQvWNBmk36sWAtF3h8gXfB2Gy8pLuT0evWW43zCTOjFeNBzBznT5yq3v014my0bUMowUd_C8SQ_0aocyyF3U7g5gxHFABNlG4-vcukiBZqc6z2rUf8ST8ITUUSf4xZtCB0yVI1_lGacRXY7YYVrnIQ9kc8-pJpn8LniVb_RGP0iMNurjh0GHAJsv40xAejEJdg-h3rNUqS4lHZK1EUC-tVcRgo-qGAREjqsEWLoGT1KwJybazv8bqm27sPJUSw

{
  "title": "Updated Plan",
  "tasks": [
    {
      "title": "Updated Task",
      "description": "New description",
      "effort": "high",
      "duration": 60,
      "priority": 5,
      "isCompleted": false
    }
  ]
}

### Read All Plans
GET http://localhost:3000/plan/read-all
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjIwMjYtMDQtMTkifQ.eyJzdWIiOiIxIiwiZW1haWwiOiJzaWxseV91c2VyIiwiaWF0IjoxNzc2NjI1NTk5LCJleHAiOjE3NzY2MjY0OTl9.BUzPkAqF_zi285gYPXBnS1op9AuiyheT8dmBhCbyfte9DLvvDTSai6noy7WuTwLsMKQWs4OtcxDjHDPRVWyGz6gtxQvWNBmk36sWAtF3h8gXfB2Gy8pLuT0evWW43zCTOjFeNBzBznT5yq3v014my0bUMowUd_C8SQ_0aocyyF3U7g5gxHFABNlG4-vcukiBZqc6z2rUf8ST8ITUUSf4xZtCB0yVI1_lGacRXY7YYVrnIQ9kc8-pJpn8LniVb_RGP0iMNurjh0GHAJsv40xAejEJdg-h3rNUqS4lHZK1EUC-tVcRgo-qGAREjqsEWLoGT1KwJybazv8bqm27sPJUSw
